services:
  - type: web
    name: portifolio
    runtime: node
    repo: https://github.com/b-ivo/Portifolio
    buildCommand: npm install && npm run build
    startCommand: npx vite preview --port 10000 --host
    autoDeploy: true
    healthCheckPath: /
